import Head from 'next/head'
import Navbar from '../components/NavBar'
import Banner from '../components/Banner'
import Hero from '../components/Hero'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/*<Navbar current="Home"/>*/}
      <Banner/>
      <Hero/>
    </div>
  )
}
